<?php
define('JQUERY_INCLUDE_METHOD_LOCAL', 0);
define('JQUERY_INCLUDE_METHOD_GOOGLE_CDN', 1);
define('JQUERY_INCLUDE_METHOD_MICROSOFT_CDN', 2);
define('JQUERY_INCLUDE_METHOD_JQUERY_CDN', 3);

define('JQUERY_VERSION', '1.11.0');